data2005_2006=[['Category', 'AllTheftNotMentionedElsewhere','TheftOutOfOrFromMotorVehicle','BurglaryAtResidentialPremises','TheftOfMotorVehicleAndMotorcycle','CommercialCrime','CommonAssault','Shoplifting','MaliciousDamageToProperty','BurglaryAtNonResidentialPremises','RobberyWithAggravatingCircumstances','DrugRelatedCrime','DrivingUnderTheInfluenceOfAlcoholOrDrugs','AssaultWithTheIntentToInflictGrievousBodilyHarm','SexualOffences','CommonRobbery','AttemptedMurder','RobberyAtResidentialPremises','Murder','IllegalPossessionOfFirearmsAndAmmunition','Carjacking','Arson','RobberyAtNonResidentialPremises','BankRobbery','RobberyOfCashInTransit','Stock-theft','Truck hijacking','RobberyOfCashInTransit'],
     ['2005-2006',3010,1111,747,626,486,478,466,440,269,237,188,183,136,87,79,17,14,11,9,7,3,2,1,1,0,0,0]]
data2006_2007=[['Category', 'AllTheftNotMentionedElsewhere','TheftOutOfOrFromMotorVehicle','BurglaryAtResidentialPremises','TheftOfMotorVehicleAndMotorcycle','CommercialCrime','CommonAssault','Shoplifting','MaliciousDamageToProperty','BurglaryAtNonResidentialPremises','RobberyWithAggravatingCircumstances','DrugRelatedCrime','DrivingUnderTheInfluenceOfAlcoholOrDrugs','AssaultWithTheIntentToInflictGrievousBodilyHarm','SexualOffences','CommonRobbery','AttemptedMurder','RobberyAtResidentialPremises','Murder','IllegalPossessionOfFirearmsAndAmmunition','Carjacking','Arson','RobberyAtNonResidentialPremises','BankRobbery','RobberyOfCashInTransit','Stock-theft','Truck hijacking','RobberyOfCashInTransit'],
     ['2006-2007',2828,1089,787,669,459,431,677,545,444,316,219,115,158,76,65,17,14,10,17,10,6,24,1,5,0,0,0]]
data2007_2008=[['Category', 'AllTheftNotMentionedElsewhere','TheftOutOfOrFromMotorVehicle','BurglaryAtResidentialPremises','TheftOfMotorVehicleAndMotorcycle','CommercialCrime','CommonAssault','Shoplifting','MaliciousDamageToProperty','BurglaryAtNonResidentialPremises','RobberyWithAggravatingCircumstances','DrugRelatedCrime','DrivingUnderTheInfluenceOfAlcoholOrDrugs','AssaultWithTheIntentToInflictGrievousBodilyHarm','SexualOffences','CommonRobbery','AttemptedMurder','RobberyAtResidentialPremises','Murder','IllegalPossessionOfFirearmsAndAmmunition','Carjacking','Arson','RobberyAtNonResidentialPremises','BankRobbery','RobberyOfCashInTransit','Stock-theft','Truck hijacking','RobberyOfCashInTransit'],
     ['2007-2008',2721,905,788,597,699,485,662,577,375,328,268,158,132,143,89,30,16,5,25,17,7,36,0,3,0,0,0]]
data2008_2009=[['Category', 'AllTheftNotMentionedElsewhere','TheftOutOfOrFromMotorVehicle','BurglaryAtResidentialPremises','TheftOfMotorVehicleAndMotorcycle','CommercialCrime','CommonAssault','Shoplifting','MaliciousDamageToProperty','BurglaryAtNonResidentialPremises','RobberyWithAggravatingCircumstances','DrugRelatedCrime','DrivingUnderTheInfluenceOfAlcoholOrDrugs','AssaultWithTheIntentToInflictGrievousBodilyHarm','SexualOffences','CommonRobbery','AttemptedMurder','RobberyAtResidentialPremises','Murder','IllegalPossessionOfFirearmsAndAmmunition','Carjacking','Arson','RobberyAtNonResidentialPremises','BankRobbery','RobberyOfCashInTransit','Stock-theft','Truck hijacking','RobberyOfCashInTransit'],
     ['2008-2009',2691,953,715,541,722,467,842,512,368,284,352,212,157,119,172,7,24,9,19,9,3,24,0,1,0,2,0]]
data2009_2010=[['Category', 'AllTheftNotMentionedElsewhere','TheftOutOfOrFromMotorVehicle','BurglaryAtResidentialPremises','TheftOfMotorVehicleAndMotorcycle','CommercialCrime','CommonAssault','Shoplifting','MaliciousDamageToProperty','BurglaryAtNonResidentialPremises','RobberyWithAggravatingCircumstances','DrugRelatedCrime','DrivingUnderTheInfluenceOfAlcoholOrDrugs','AssaultWithTheIntentToInflictGrievousBodilyHarm','SexualOffences','CommonRobbery','AttemptedMurder','RobberyAtResidentialPremises','Murder','IllegalPossessionOfFirearmsAndAmmunition','Carjacking','Arson','RobberyAtNonResidentialPremises','BankRobbery','RobberyOfCashInTransit','Stock-theft','Truck hijacking','RobberyOfCashInTransit'],
     ['2009-2010',2691,953,715,541,722,467,842,512,368,284,352,212,157,119,172,7,24,9,19,9,3,24,0,1,0,2]]
data2010_2011=[['Category', 'AllTheftNotMentionedElsewhere','TheftOutOfOrFromMotorVehicle','BurglaryAtResidentialPremises','TheftOfMotorVehicleAndMotorcycle','CommercialCrime','CommonAssault','Shoplifting','MaliciousDamageToProperty','BurglaryAtNonResidentialPremises','RobberyWithAggravatingCircumstances','DrugRelatedCrime','DrivingUnderTheInfluenceOfAlcoholOrDrugs','AssaultWithTheIntentToInflictGrievousBodilyHarm','SexualOffences','CommonRobbery','AttemptedMurder','RobberyAtResidentialPremises','Murder','IllegalPossessionOfFirearmsAndAmmunition','Carjacking','Arson','RobberyAtNonResidentialPremises','BankRobbery','RobberyOfCashInTransit','Stock-theft','Truck hijacking','RobberyOfCashInTransit'],
     ['2010-2011',2180,1338,962,550,675,432,682,584,340,263,511,230,164,78,583,8,22,3,24,3,2,15,0,0,0,0,0]]
data2011_2012=[['Category', 'AllTheftNotMentionedElsewhere','TheftOutOfOrFromMotorVehicle','BurglaryAtResidentialPremises','TheftOfMotorVehicleAndMotorcycle','CommercialCrime','CommonAssault','Shoplifting','MaliciousDamageToProperty','BurglaryAtNonResidentialPremises','RobberyWithAggravatingCircumstances','DrugRelatedCrime','DrivingUnderTheInfluenceOfAlcoholOrDrugs','AssaultWithTheIntentToInflictGrievousBodilyHarm','SexualOffences','CommonRobbery','AttemptedMurder','RobberyAtResidentialPremises','Murder','IllegalPossessionOfFirearmsAndAmmunition','Carjacking','Arson','RobberyAtNonResidentialPremises','BankRobbery','RobberyOfCashInTransit','Stock-theft','Truck hijacking','RobberyOfCashInTransit'],
     ['2011-2012',2435,1586,1046,518,798,408,672,394,456,341,735,332,177,68,471,8,29,19,17,7,5,16,0,0,0,0,92]]
data2012_2013=[['Category', 'AllTheftNotMentionedElsewhere','TheftOutOfOrFromMotorVehicle','BurglaryAtResidentialPremises','TheftOfMotorVehicleAndMotorcycle','CommercialCrime','CommonAssault','Shoplifting','MaliciousDamageToProperty','BurglaryAtNonResidentialPremises','RobberyWithAggravatingCircumstances','DrugRelatedCrime','DrivingUnderTheInfluenceOfAlcoholOrDrugs','AssaultWithTheIntentToInflictGrievousBodilyHarm','SexualOffences','CommonRobbery','AttemptedMurder','RobberyAtResidentialPremises','Murder','IllegalPossessionOfFirearmsAndAmmunition','Carjacking','Arson','RobberyAtNonResidentialPremises','BankRobbery','RobberyOfCashInTransit','Stock-theft','Truck hijacking','RobberyOfCashInTransit'],
     ['2012-2013',2231,1490,1036,582,663,395,587,267,440,354,776,359,153,46,487,15,24,10,19,9,9,28,0,0,0,1,19]]
data2013_2014=[['Category', 'AllTheftNotMentionedElsewhere','TheftOutOfOrFromMotorVehicle','BurglaryAtResidentialPremises','TheftOfMotorVehicleAndMotorcycle','CommercialCrime','CommonAssault','Shoplifting','MaliciousDamageToProperty','BurglaryAtNonResidentialPremises','RobberyWithAggravatingCircumstances','DrugRelatedCrime','DrivingUnderTheInfluenceOfAlcoholOrDrugs','AssaultWithTheIntentToInflictGrievousBodilyHarm','SexualOffences','CommonRobbery','AttemptedMurder','RobberyAtResidentialPremises','Murder','IllegalPossessionOfFirearmsAndAmmunition','Carjacking','Arson','RobberyAtNonResidentialPremises','BankRobbery','RobberyOfCashInTransit','Stock-theft','Truck hijacking','RobberyOfCashInTransit'],
     ['2013-2014',2249,1465,1193,560,607,404,611,314,433,546,725,218,123,54,482,14,43,11,13,18,3,47,0,0,0,0,7]]
data2014_2015=[['Category', 'AllTheftNotMentionedElsewhere','TheftOutOfOrFromMotorVehicle','BurglaryAtResidentialPremises','TheftOfMotorVehicleAndMotorcycle','CommercialCrime','CommonAssault','Shoplifting','MaliciousDamageToProperty','BurglaryAtNonResidentialPremises','RobberyWithAggravatingCircumstances','DrugRelatedCrime','DrivingUnderTheInfluenceOfAlcoholOrDrugs','AssaultWithTheIntentToInflictGrievousBodilyHarm','SexualOffences','CommonRobbery','AttemptedMurder','RobberyAtResidentialPremises','Murder','IllegalPossessionOfFirearmsAndAmmunition','Carjacking','Arson','RobberyAtNonResidentialPremises','BankRobbery','RobberyOfCashInTransit','Stock-theft','Truck hijacking','RobberyOfCashInTransit'],
     ['2014-2015',2136,1732,1013,529,520,420,594,312,417,526,766,135,141,50,485,19,29,6,19,18,0,45,0,2,0,0,4]] 
data2015_2016=[['Category', 'AllTheftNotMentionedElsewhere','TheftOutOfOrFromMotorVehicle','BurglaryAtResidentialPremises','TheftOfMotorVehicleAndMotorcycle','CommercialCrime','CommonAssault','Shoplifting','MaliciousDamageToProperty','BurglaryAtNonResidentialPremises','RobberyWithAggravatingCircumstances','DrugRelatedCrime','DrivingUnderTheInfluenceOfAlcoholOrDrugs','AssaultWithTheIntentToInflictGrievousBodilyHarm','SexualOffences','CommonRobbery','AttemptedMurder','RobberyAtResidentialPremises','Murder','IllegalPossessionOfFirearmsAndAmmunition','Carjacking','Arson','RobberyAtNonResidentialPremises','BankRobbery','RobberyOfCashInTransit','Stock-theft','Truck hijacking','RobberyOfCashInTransit'],
     ['2015-2016',1839,1487,853,389,550,376,587,298,341,461,1456,159,122,62,400,8,31,5,7,26,2,31,0,0,0,0,18]]




                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                        
